version: "3.3"

services:

  nginx: 
    image: nginx:latest
    container_name: reverproxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  redis:

    image: redis:alpine

    ports:
      - "6379"
    networks:
      - frontend

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - backend

  vote:

    image: dockersamples/examplevotingapp_vote:before

    ports:

      - 5000:80

    depends_on:

      - redis
    networks:
      - frontend

 

  # Web UI to count voting results

  result:

    image: dockersamples/examplevotingapp_result:before

    ports:

      - 5001:80

    depends_on:

      - db
    networks:
      - backend

 

  # Worker service to read from message queue

  worker:

    image: dockersamples/examplevotingapp_worker
    networks:
      - backend
      - frontend

volumes:
  db-data:
  - ./nginx.conf:/etc/nginx/nginx.conf
    
networks:
  frontend:
  backend:
